---
title: "ASHRAE Energy Prediction - Exploratory Data Analysis"
output: html_notebook
---


## Setup    
  Load the relevant libraries.
```{r message=TRUE, warning=TRUE}

# rm(list = ls())
# .rs.restartR()


# data munging
library("tidyverse")
library("data.table")

# munge dates
library("lubridate")

# get tweets
# library("rtweet")

# NLP
# library("tidytext")
# library("syuzhet")
# library("googleLanguageR")

# graph analyses
# library("tidygraph")
# library("ggraph")

# # feature engineering and data prep
# library("recipes")
# library("caret")
# library("DMwR")
# 
# # to explore missing data
# library("visdat")
# library("naniar")
# 
# # modeling
# library("h2o")

```
  
    
  Session Info.
```{r}

sessionInfo()

```


  Setup the root directory.
```{r "setup", include = FALSE}

require("knitr")

# Use when running from AWS
# opts_knit$set(root.dir = "/home/rstudio/Dropbox/_AWS/twitter_dc_metro2/")

# Use when running from laptop
opts_knit$set(root.dir = "/Users/mdturse/Desktop/Analytics/ashrae_energy_prediction/")

# Use when running from Sparkfund laptop
# opts_knit$set(root.dir = "/Users/danielturse/Desktop/Projects/ashrae_energy_prediction/")

```
  
    
  Setting `wd` as the working directory.
```{r}

wd <- getwd()

wd

```


## Get the data  

```{r}

file_names <-
  list.files(path = paste0(wd,
                           "/Data/Raw"
                           )
             )

files_list <-
  file_names %>% 
  # map(~read_csv(file = paste0(wd,
  #                             "/Data/Raw/",
  #                             .x
  #                             )
  #               )
  #     )
  map(~fread(file = paste0(wd,
                           "/Data/Raw/",
                           .x
                           )
             )
      )

names(files_list) <- file_names

glimpse(files_list)

```



```{r}

cnts_bldg_mtr <-
  files_list$train.csv %>% 
  count(building_id,
        meter,
        # timestamp
        ) %>% 
  arrange(building_id,
          meter
          )

cnts_bldg_mtr

cnts_bldg_mtr_reading_abv_zero <-
  files_list$train.csv %>% 
  filter(meter_reading > 0) %>% 
  count(building_id,
        meter,
        # timestamp
        ) %>% 
  arrange(building_id,
          meter
          )

cnts_bldg_mtr_reading_abv_zero


cnts_mtr <-
  cnts_bldg_mtr %>% 
  count(meter,
        wt = n
        )

cnts_mtr


cnts_mtr_reading_abv_zero <-
  cnts_bldg_mtr_reading_abv_zero %>% 
  count(meter,
        wt = n
        )

cnts_mtr_reading_abv_zero


files_list$building_metadata.csv %>% 
  count(primary_use)

```


```{r}

joined_data <-
  # files_list$train.csv %>%
  # left_join(y = files_list$building_metadata.csv,
  #           by = c("building_id" = "building_id")
  #           ) %>%
  # left_join(y = files_list$weather_train.csv,
  #           by = c("site_id" = "site_id",
  #                  "timestamp" = "timestamp"
  #                  )
  #           ) %>%
  # mutate(timestamp = as_datetime(timestamp),
  #        meter_reading_log = log(meter_reading + 1)
  #        ) %>%
  # mutate_if(is_character, factor) %>%
  # arrange(building_id,
  #         meter,
  #         timestamp
  #         )
  merge(x = files_list$train.csv,
        y = files_list$building_metadata.csv,
        by.x = "building_id",
        by.y = "building_id",
        all.x = TRUE
        )

joined_data <-
  merge(x = joined_data,
        y = files_list$weather_train.csv,
        by.x = c("site_id", "timestamp"),
        by.y = c("site_id", "timestamp"),
        all.x = TRUE
        )

joined_data <-
  joined_data[ , `:=` (timestamp = as_datetime(timestamp),
                       primary_use = factor(primary_use),
                       meter_reading_log = log(meter_reading + 1)
                       )
               ] %>% 
  setkey(building_id,
         meter,
         timestamp
         )


# dim(joined_data)
class(joined_data)
str(joined_data)
glimpse(joined_data)
# View(head(joined_data, 1000))

```


```{r}

split_first_10_bldgs <-
  joined_data[building_id < 10] %>% 
  split(.$building_id)

# split_first_10_bldgs$`0` %>% 
#   pivot_longer(cols = c(meter_reading, meter_reading_log),
#                names_to = "reading_type",
#                values_to = "reading_value"
#                ) %>% 
#   View()

line_plots <-
  pmap(.l = list(a = split_first_10_bldgs,
                 b = names(split_first_10_bldgs)
                 ),
       .f = function(a, b) {
         a %>% 
           pivot_longer(cols = c(meter_reading, meter_reading_log),
                        names_to = "reading_type",
                        values_to = "reading_value"
                        ) %>% 
           ggplot(#data = a,
                  aes(x = timestamp,
                      y = reading_value,
                      # y = meter_reading_log,
                      colour = factor(meter)
                      )
                  ) +
           geom_line() +
           facet_wrap(vars(meter, reading_type),
                      scales = "free"
                      ) +
           labs(title = paste0("building_id: ", b)
                ) +
           theme_minimal() +
           theme(legend.position = "none")
         }
       )

line_plots



```


```{r}

joined_data %>% 
  count(primary_use) %>% 
  left_join(joined_data %>% 
              filter(meter_reading_log > 0) %>% 
              count(primary_use) %>% 
              rename(n_reading_abv_0 = n),
            by = "primary_use"
            ) %>% 
  mutate(n_reading_abv_0_pct = n_reading_abv_0 / n)
            
```
  
    
  Inspect if train and test have the same combinations of `building_id` and `meter`.
```{r}

bldg_mtr_train <-
  files_list$train.csv[ ,
                       list(building_id, meter)
                       ][ ,
                         bldg_mtr := paste0(building_id, "_", meter)
                         ][order(building_id,
                                 meter
                                 )
                           ]

message("bldg_mtr_train")
str(bldg_mtr_train)


bldg_mtr_test <-
  files_list$test.csv[ ,
                       list(building_id, meter)
                       ][ ,
                          bldg_mtr := paste0(building_id, "_", meter)
                          ][order(building_id,
                                  meter
                                  )
                            ]

message("bldg_mtr_test")
str(bldg_mtr_test)


message("setdiff")
setdiff(x = unique(bldg_mtr_train$bldg_mtr),
        y = unique(bldg_mtr_test$bldg_mtr)
        )

```

